import { useState } from 'react'
import { PageHeader, Card, PrimaryButton, SecondaryButton, Badge } from '../../../../../shared/components/ui'
const steps=['Client & Contact','Identity & Documents','Clinical Intake','Insurance & Package','Consents & Signatures','Care Team & Room','Review & Admit']
export default function AdmissionWizard(){
 const [step,setStep]=useState(0)
 return <><PageHeader title="New Admission" subtitle="Guided digital onboarding • Draft auto-save ready"/>
 <div className="wizard"><aside className="stepper">{steps.map((s,i)=><button key={s} onClick={()=>setStep(i)} className={i===step?'active':i<step?'done':''}><span>{i<step?'✓':i+1}</span><div><strong>{s}</strong><small>{i<step?'Complete':i===step?'In progress':'Not started'}</small></div></button>)}</aside>
 <div className="wizard-body"><Card title={steps[step]}>
 {step===0&&<div className="form-grid"><label>Existing client search<input placeholder="Mobile / email / client ID"/></label><label>Full name<input defaultValue="Rohan Sen"/></label><label>Date of birth<input type="date"/></label><label>Gender<select><option>Select</option><option>Male</option><option>Female</option><option>Other</option></select></label><label>Mobile<input/></label><label>Email<input/></label><label className="span-2">Address<textarea rows={3}/></label></div>}
 {step===1&&<div className="upload-zone"><h3>Scan or upload identity document</h3><p>Aadhaar, Passport or National ID. Capture front/back where applicable.</p><div className="button-row"><PrimaryButton>Open Camera / Scanner</PrimaryButton><SecondaryButton>Upload File</SecondaryButton></div><div className="doc-preview"><Badge tone="success">Aadhaar front uploaded</Badge><span>Identity number should be masked in standard UI views.</span></div></div>}
 {step===2&&<div className="form-grid"><label>Primary reason for admission<textarea rows={4}/></label><label>Mental health history<textarea rows={4}/></label><label>Addiction history<textarea rows={4}/></label><label>Current medications<textarea rows={4}/></label><label>Allergies<textarea rows={3}/></label><label>Emergency risk / safety notes<textarea rows={3}/></label></div>}
 {step===3&&<div className="form-grid"><label>Treatment package<select><option>30-Day Residential</option><option>15-Day Detox</option><option>10-Day Detox</option></select></label><label>Payer type<select><option>Self Pay</option><option>Insurance</option></select></label><label>Insurance provider<input/></label><label>Pre-auth reference<input/></label></div>}
 {step===4&&<div className="signature-list">{['Consent for Treatment','Privacy & Confidentiality','Family Access Authorization','Telehealth / Recording Consent','Liability Waiver'].map((x,i)=><div key={x}><span><strong>{x}</strong><small>Version-controlled form template</small></span><Badge tone={i<2?'success':'warning'}>{i<2?'Signed':'Pending'}</Badge><button className="link-btn">{i<2?'View':'Open & Sign'}</button></div>)}</div>}
 {step===5&&<div className="form-grid"><label>Centre<select><option>Mumbai Centre</option></select></label><label>Room / Bed<select><option>Suite M-204</option></select></label><label>Primary psychiatrist<select><option>Dr. N. Sharma</option></select></label><label>Psychologist<select><option>Riya Kapoor</option></select></label><label>Nutritionist<select><option>Anita Rao</option></select></label><label>Residential care team<select><option>Team A</option></select></label></div>}
 {step===6&&<div className="review-box"><h3>Admission ready for final review</h3><p>Validate mandatory identity, clinical, package, consent, location, room and care-team data before creating the admission.</p><Badge tone="warning">2 optional signatures pending</Badge></div>}
 <div className="wizard-actions"><SecondaryButton onClick={()=>setStep(Math.max(0,step-1))}>Back</SecondaryButton>{step<steps.length-1?<PrimaryButton onClick={()=>setStep(step+1)}>Save & Continue</PrimaryButton>:<PrimaryButton>Confirm Admission</PrimaryButton>}</div>
 </Card></div></div></>
}
